name = "ai-error-query-builder"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables (add these via wrangler CLI or dashboard)
# OPENAI_API_KEY = "your-key-here"
# AI_GATEWAY_ACCOUNT_ID = "your-account-id" (optional)
# AI_GATEWAY_ID = "your-gateway-id" (optional)

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

# D1 Database (optional - for storing query history)
# [[d1_databases]]
# binding = "DB"
# database_name = "ai-error-queries"
# database_id = "your-database-id"

# AI Gateway configuration (optional but recommended)
# This provides caching, rate limiting, and analytics for OpenAI API calls
# Setup: https://developers.cloudflare.com/ai-gateway/
